# Build & publish docker images
name: Dockerhub

on:
  push:
    tags: [v*]
    branches: [ main ]


jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Set tag name
        run: |
          if [[ ${{ github.ref_type }} == "tag" ]]; then
            echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV  
          else
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV  
          fi
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{env.IMAGE_TAG}}
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
